package com.kanayaya.BitrixFluentWebhooks.model.enums;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public enum Country {
    RUSSIA(1, "Russia", "Россия"),
    AZERBAIJAN(2, "Azerbaijan", "Азербайджан"),
    ARMENIA(3, "Armenia", "Армения"),
    BELARUS(4, "Belarus", "Беларусь"),
    GEORGIA(5, "Georgia", "Грузия"),
    KAZAKHSTAN(6, "Kazakhstan", "Казахстан"),
    KYRGYZSTAN(7, "Kyrgyzstan", "Киргизия"),
    LATVIA(8, "Latvia", "Латвия"),
    LITHUANIA(9, "Lithuania", "Литва"),
    MOLDOVA(10, "Moldova", "Молдавия"),
    TAJIKISTAN(11, "Tajikistan", "Таджикистан"),
    TURKMENISTAN(12, "Turkmenistan", "Туркменистан"),
    UZBEKISTAN(13, "Uzbekistan", "Узбекистан"),
    UKRAINE(14, "Ukraine", "Украина"),
    ESTONIA(15, "Estonia", "Эстония"),
    AUSTRALIA(16, "Australia", "Австралия"),
    AUSTRIA(17, "Austria", "Австрия"),
    ALBANIA(18, "Albania", "Албания"),
    ALGERIA(19, "Algeria", "Алжир"),
    ANGOLA(20, "Angola", "Ангола"),
    UNITED_ARAB_EMIRATES(21, "United Arab Emirates", "Арабские Эмираты"),
    ARGENTINA(22, "Argentina", "Аргентина"),
    ARUBA(23, "Aruba", "Аруба"),
    AFGHANISTAN(24, "Afghanistan", "Афганистан"),
    BAHAMAS(25, "Bahamas", "Багамские острова"),
    BANGLADESH(26, "Bangladesh", "Бангладеш"),
    BARBADOS(27, "Barbados", "Барбадос"),
    BELGIUM(28, "Belgium", "Бельгия"),
    BENIN(29, "Benin", "Бенин"),
    BERMUDA(30, "Bermuda", "Бермудские острова"),
    BULGARIA(31, "Bulgaria", "Болгария"),
    BOLIVIA(32, "Bolivia", "Боливия"),
    BOSNIA_AND_HERZEGOWINA(33, "Bosnia and Herzegowina", "Босния и Герцеговина"),
    BRAZIL(34, "Brazil", "Бразилия"),
    BRUNEI_DARUSSALAM(35, "Brunei Darussalam", "Бруней"),
    UNITED_KINGDOM(36, "United Kingdom", "Великобритания"),
    HUNGARY(37, "Hungary", "Венгрия"),
    VENEZUELA(38, "Venezuela", "Венесуэлла"),
    VIET_NAM(39, "Viet Nam", "Вьетнам"),
    HAITI(40, "Haiti", "Гаити"),
    GAMBIA(41, "Gambia", "Гамбия"),
    HONDURAS(42, "Honduras", "Гондурас"),
    GUADELOUPE(43, "Guadeloupe", "Гваделупа"),
    GUATEMALA(44, "Guatemala", "Гватемала"),
    GUINEA(45, "Guinea", "Гвинея"),
    GERMANY(46, "Germany", "Германия"),
    GIBRALTAR(47, "Gibraltar", "Гибралтар"),
    NETHERLANDS(48, "Netherlands", "Нидерланды"),
    HONG_KONG(49, "Hong Kong", "Гонконг"),
    GRENADA(50, "Grenada", "Гренада"),
    GREENLAND(51, "Greenland", "Гренландия"),
    GREECE(52, "Greece", "Греция"),
    GUYANA(53, "Guyana", "Гуана"),
    DENMARK(54, "Denmark", "Дания"),
    DOMINICAN_REPUBLIC(55, "Dominican Republic", "Доминиканская Республика"),
    EGYPT(56, "Egypt", "Египет"),
    ZAIRE(57, "Zaire", "Демократическая республика Конго"),
    ZAMBIA(58, "Zambia", "Замбия"),
    ZIMBABWE(59, "Zimbabwe", "Зимбабве"),
    ISRAEL(60, "Israel", "Израиль"),
    INDIA(61, "India", "Индия"),
    INDONESIA(62, "Indonesia", "Индонезия"),
    JORDAN(63, "Jordan", "Иордания"),
    IRAQ(64, "Iraq", "Ирак"),
    IRAN(65, "Iran", "Иран"),
    IRELAND(66, "Ireland", "Ирландия"),
    ICELAND(67, "Iceland", "Исландия"),
    SPAIN(68, "Spain", "Испания"),
    ITALY(69, "Italy", "Италия"),
    YEMEN(70, "Yemen", "Йемен"),
    CAYMAN_ISLANDS(71, "Cayman Islands", "Каймановы острова"),
    CAMEROON(72, "Cameroon", "Камерун"),
    CANADA(73, "Canada", "Канада"),
    KENYA(74, "Kenya", "Кения"),
    CYPRUS(75, "Cyprus", "Кипр"),
    CHINA(76, "China", "Китай"),
    COLOMBIA(77, "Colombia", "Колумбия"),
    CAMBODIA(78, "Cambodia", "Камбоджа"),
    CONGO(79, "Congo", "Конго"),
    KOREA_SOUTH(80, "Korea (South)", "Корея (Южная)"),
    COSTA_RICA(81, "Costa Rica", "Коста Рика"),
    CUBA(82, "Cuba", "Куба"),
    KUWAIT(83, "Kuwait", "Кувейт"),
    LIBERIA(84, "Liberia", "Либерия"),
    LIECHTENSTEIN(85, "Liechtenstein", "Лихтенштейн"),
    LUXEMBOURG(86, "Luxembourg", "Люксембург"),
    MAURITANIA(87, "Mauritania", "Мавритания"),
    MADAGASCAR(88, "Madagascar", "Мадагаскар"),
    MACEDONIA(89, "Macedonia", "Македония"),
    MALAYSIA(90, "Malaysia", "Малайзия"),
    MALI(91, "Mali", "Мали"),
    MALTA(92, "Malta", "Мальта"),
    MEXICO(93, "Mexico", "Мексика"),
    MOZAMBIQUE(94, "Mozambique", "Мозамбик"),
    MONACO(95, "Monaco", "Монако"),
    MONGOLIA(96, "Mongolia", "Монголия"),
    MOROCCO(97, "Morocco", "Марокко"),
    NAMIBIA(98, "Namibia", "Намибия"),
    NEPAL(99, "Nepal", "Непал"),
    NIGERIA(100, "Nigeria", "Нигерия"),
    NICARAGUA(102, "Nicaragua", "Никарагуа"),
    NEW_ZEALAND(103, "New Zealand", "Новая Зеландия"),
    NORWAY(104, "Norway", "Норвегия"),
    PAKISTAN(105, "Pakistan", "Пакистан"),
    PANAMA(106, "Panama", "Панама"),
    PAPUA_NEW_GUINEA(107, "Papua New Guinea", "Папуа Новая Гвинея"),
    PARAGUAY(108, "Paraguay", "Парагвай"),
    PERU(109, "Peru", "Перу"),
    POLAND(110, "Poland", "Польша"),
    PORTUGAL(111, "Portugal", "Португалия"),
    PUERTO_RICO(112, "Puerto Rico", "Пуэрто Рико"),
    ROMANIA(113, "Romania", "Румыния"),
    SAUDI_ARABIA(114, "Saudi Arabia", "Саудовская Аравия"),
    SENEGAL(115, "Senegal", "Сенегал"),
    SINGAPORE(116, "Singapore", "Сингапур"),
    SYRIA(117, "Syria", "Сирия"),
    SLOVAKIA(118, "Slovakia", "Словакия"),
    SLOVENIA(119, "Slovenia", "Словения"),
    SOMALIA(120, "Somalia", "Сомали"),
    SUDAN(121, "Sudan", "Судан"),
    USA(122, "USA", "США"),
    TAIWAN(123, "Taiwan", "Тайвань"),
    THAILAND(124, "Thailand", "Таиланд"),
    TRINIDAD_AND_TOBAGO(125, "Trinidad and Tobago", "Тринидад и Тобаго"),
    TUNISIA(126, "Tunisia", "Тунис"),
    TURKEY(127, "Turkey", "Турция"),
    UGANDA(128, "Uganda", "Уганда"),
    URUGUAY(129, "Uruguay", "Уругвай"),
    PHILIPPINES(130, "Philippines", "Филиппины"),
    FINLAND(131, "Finland", "Финляндия"),
    FRANCE(132, "France", "Франция"),
    CHAD(133, "Chad", "Чад"),
    CZECHIA(134, "Czechia", "Чехия"),
    CHILE(135, "Chile", "Чили"),
    SWITZERLAND(136, "Switzerland", "Швейцария"),
    SWEDEN(137, "Sweden", "Швеция"),
    SRI_LANKA(138, "Sri Lanka", "Шри-Ланка"),
    ECUADOR(139, "Ecuador", "Эквадор"),
    ETHIOPIA(140, "Ethiopia", "Эфиопия"),
    SOUTH_AFRICAN_REPUBLIC(141, "South African Republic", "ЮАР"),
    SERBIA(142, "Serbia", "Сербия"),
    JAMAICA(143, "Jamaica", "Ямайка"),
    JAPAN(144, "Japan", "Япония"),
    BAHRAIN(145, "Bahrain", "Бахрейн"),
    ANDORRA(146, "Andorra", "Андорра"),
    BELIZE(147, "Belize", "Белиз"),
    BHUTAN(148, "Bhutan", "Бутан"),
    BOTSWANA(149, "Botswana", "Ботсвана"),
    BURKINA_FASO(150, "Burkina Faso", "Буркина Фасо"),
    BURUNDI(151, "Burundi", "Бурунди"),
    CENTRAL_AFRICAN_REPUBLIC(152, "Central African Republic", "Центральноафриканская Республика"),
    COMOROS(153, "Comoros", "Коморос"),
    COTE_D_IVOIRE(154, "Cote D'ivoire", "Кот-Д`ивуар"),
    DJIBOUTI(155, "Djibouti", "Джибути"),
    EAST_TIMOR(156, "East Timor", "Восточный Тимор"),
    EL_SALVADOR(157, "El Salvador", "Эль Сальвадор"),
    EQUATORIAL_GUINEA(158, "Equatorial Guinea", "Экваториальная Гвинея"),
    ERITREA(159, "Eritrea", "Эритрея"),
    FIJI(160, "Fiji", "Фиджи"),
    GABON(161, "Gabon", "Габон"),
    GHANA(162, "Ghana", "Гана"),
    GUINEA_BISSAU(163, "Guinea-bissau", "Гвинея-Биссау"),
    KOREA_NORTH(164, "Korea (North)", "Корея (Северная)"),
    LEBANON(165, "Lebanon", "Ливан"),
    LESOTHO(166, "Lesotho", "Лесото"),
    LIBYA(167, "Libya", "Ливия"),
    MALDIVES(168, "Maldives", "Мальдивы"),
    MARSHALL_ISLANDS(169, "Marshall Islands", "Маршалские острова"),
    NIGER(170, "Niger", "Нигер"),
    OMAN(171, "Oman", "Оман"),
    QATAR(172, "Qatar", "Катар"),
    RWANDA(173, "Rwanda", "Руанда"),
    SAMOA(174, "Samoa", "Самоа"),
    SEYCHELLES(175, "Seychelles", "Сейшеллы"),
    SIERRA_LEONE(176, "Sierra Leone", "Сьерра-Леоне"),
    SURINAME(177, "Suriname", "Суринам"),
    SWAZILAND(178, "Swaziland", "Свазиленд"),
    TANZANIA(179, "Tanzania", "Танзания"),
    WESTERN_SAHARA(180, "Western Sahara", "Западная Сахара"),
    CROATIA(181, "Croatia", "Хорватия"),
    ANGUILLA(182, "Anguilla", "Ангилья"),
    ANTARCTICA(183, "Antarctica", "Антарктида"),
    ANTIGUA_AND_BARBUDA(184, "Antigua and Barbuda", "Антигуа и Барбуда"),
    BOUVET_ISLAND(185, "Bouvet Island", "Остров Буве"),
    BRITISH_INDIAN_OCEAN_TERRITORY(186, "British Indian Ocean Territory", "Британские территории в Индийском Океане"),
    BRITISH_VIRGIN_ISLANDS(187, "British Virgin Islands", "Британские Виргинские острова"),
    MYANMAR(188, "Myanmar", "Мьянма"),
    CAPE_VERDE(189, "Cape Verde", "Кабо-Верде"),
    CHRISTMAS_ISLAND(190, "Christmas Island", "Остров Рождества"),
    COCOS_ISLANDS(191, "Cocos Islands", "Кокосовые острова"),
    COOK_ISLANDS(192, "Cook Islands", "Острова Кука"),
    DOMINICA(193, "Dominica", "Доминика"),
    FALKLAND_ISLANDS(194, "Falkland Islands", "Фолклендские острова"),
    FAEROE_ISLANDS(195, "Faeroe Islands", "Фарерские острова"),
    FRENCH_GUIANA(196, "French Guiana", "Гвиана"),
    FRENCH_POLYNESIA(197, "French Polynesia", "Французская Полинезия"),
    FRENCH_ANTARCTIC(198, "French Antarctic", "Южные Французские территории"),
    HEARD_AND_MCDONALD_ISLANDS(199, "Heard and McDonald Islands", "Острова Херд и Макдоналд"),
    KIRIBATI(200, "Kiribati", "Кирибати"),
    LAOS(201, "Laos", "Лаос"),
    MACAU(202, "Macau", "Макао"),
    MALAWI(203, "Malawi", "Малави"),
    MARTINIQUE(204, "Martinique", "Мартиника"),
    MAURITIUS(205, "Mauritius", "Маврикий"),
    MAYOTTE(206, "Mayotte", "Майотта"),
    MICRONESIA(207, "Micronesia", "Микронезия"),
    MONTSERRAT(208, "Montserrat", "Монтсеррат"),
    NAURU(209, "Nauru", "Науру"),
    NETHERLANDS_ANTILLES(210, "Netherlands Antilles", "Антильские острова"),
    NEW_CALEDONIA(211, "New Caledonia", "Новая Каледония"),
    NIUE(212, "Niue", "Ниуэ"),
    NORFOLK_ISLAND(213, "Norfolk Island", "Остров Норфолк"),
    PALAU(214, "Palau", "Палау"),
    PALESTINE(215, "Palestine", "Палестина"),
    PITCAIRN_ISLANDS(216, "Pitcairn Islands", "Остров Питкэрн"),
    REUNION(217, "Reunion", "Реюньон"),
    SAINT_HELENA(218, "Saint Helena", "Остров Св.Елены"),
    SAINT_KITTS_AND_NEVIS(219, "Saint Kitts and Nevis", "Острова Сент-Киттс и Невис"),
    SAINT_LUCIA(220, "Saint Lucia", "Санта-Лючия"),
    SAINT_PIERRE_AND_MIQUELON(221, "Saint-Pierre and Miquelon", "Острова Сен-Пьер и Микелон"),
    SAINT_VINCENT_AND_THE_GRENADINES(222, "Saint Vincent and the Grenadines", "Сент-Винсент и Гренадины"),
    SAN_MARINO(223, "San Marino", "Сан-Марино"),
    SOLOMON_ISLANDS(224, "Solomon Islands", "Соломоновы острова"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS(225, "South Georgia and the South Sandwich Islands", "Южная Георгия и Южные Сандвичевы острова"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS(226, "Svalbard and Jan Mayen Islands", "Острова Шпицберген и Ян-Майен"),
    TOGO(227, "Togo", "Того"),
    TOKELAU(228, "Tokelau", "Токелау"),
    TONGA(229, "Tonga", "Тонга"),
    TURKS_CAICOS_ISLANDS(230, "Turks Caicos Islands", "Острова Тёркс и Кайкос"),
    TUVALU(231, "Tuvalu", "Тувалу"),
    US_VIRGIN_ISLANDS(232, "U.S. Virgin Islands", "Американские Виргинские острова"),
    VANUATU(233, "Vanuatu", "Вануату"),
    VATICAN_CITY(234, "Vatican City", "Ватикан"),
    WALLIS_AND_FUTUNA_ISLANDS(235, "Wallis and Futuna Islands", "Острова Уоллис и Футуна"),
    MONTENEGRO(236, "Montenegro", "Черногория"),
    ;
    private final int id;
    private final String enName;
    private final String ruName;

    Country(int id, String enName, String ruName) {
        this.id = id;
        this.enName = enName;
        this.ruName = ruName;
    }

    public int getId() {
        return id;
    }

    public String getEnName() {
        return enName;
    }

    public String getRuName() {
        return ruName;
    }

    @Override
    public String toString() {
        return Integer.toString(id);
    }

    private static final Map<Integer, Country> byId = new HashMap<>();
    static {
        Arrays.stream(values()).forEach(c->byId.put(c.id, c));
    }

    public static Country getById(Integer id) {
        return byId.get(id);
    }
}
