package com.kanayaya.BitrixFluentWebhooks.api.methods;

import com.kanayaya.BitrixFluentWebhooks.BitrixRestClient;
import com.kanayaya.BitrixFluentWebhooks.api.methods.crm.Documentgenerator;
import com.kanayaya.BitrixFluentWebhooks.api.methods.crm.Enum;
import com.kanayaya.BitrixFluentWebhooks.api.methods.crm.*;

public class Crm {
    public final Livefeedmessage livefeedmessage;
    public final Deal deal;
    public final Externalchannel externalchannel;
    public final Activity activity;
    public final Catalog catalog;
    public final Type type;
    public final Tracking tracking;
    public final Persontype persontype;
    public final Documentgenerator documentgenerator;
    public final Button button;
    public final Automatedsolution automatedsolution;
    public final Automation automation;
    public final Quote quote;
    public final Userfield userfield;
    public final Contact contact;
    public final Addresstype addresstype;
    public final Currency currency;
    public final Company company;
    public final Settings settings;
    public final Product product;
    public final Item item;
    public final Address address;
    public final Orderentity orderentity;
    public final Paysystem paysystem;
    public final Vat vat;
    public final Duplicate duplicate;
    public final Productsection productsection;
    public final Webform webform;
    public final Requisite requisite;
    public final Enum enum_;
    public final Lead lead;
    public final Site site;
    public final Measure measure;
    public final Sitebutton sitebutton;
    public final Productrow productrow;
    public final Multifield multifield;
    public final Timeline timeline;
    public final Invoice invoice;
    public final Calllist calllist;
    public final Category category;
    public final Dealcategory dealcategory;
    public final Status status;
    private final BitrixRestClient client;

    public Crm(BitrixRestClient client) {
        this.client = client;
        livefeedmessage = new Livefeedmessage(client);
        deal = new Deal(client);
        externalchannel = new Externalchannel(client);
        activity = new Activity(client);
        catalog = new Catalog(client);
        type = new Type(client);
        tracking = new Tracking(client);
        persontype = new Persontype(client);
        documentgenerator = new Documentgenerator(client);
        button = new Button(client);
        automatedsolution = new Automatedsolution(client);
        automation = new Automation(client);
        quote = new Quote(client);
        userfield = new Userfield(client);
        contact = new Contact(client);
        addresstype = new Addresstype(client);
        currency = new Currency(client);
        company = new Company(client);
        settings = new Settings(client);
        product = new Product(client);
        item = new Item(client);
        address = new Address(client);
        orderentity = new Orderentity(client);
        paysystem = new Paysystem(client);
        vat = new Vat(client);
        duplicate = new Duplicate(client);
        productsection = new Productsection(client);
        webform = new Webform(client);
        requisite = new Requisite(client);
        enum_ = new Enum(client);
        lead = new Lead(client);
        site = new Site(client);
        measure = new Measure(client);
        sitebutton = new Sitebutton(client);
        productrow = new Productrow(client);
        multifield = new Multifield(client);
        timeline = new Timeline(client);
        invoice = new Invoice(client);
        calllist = new Calllist(client);
        category = new Category(client);
        dealcategory = new Dealcategory(client);
        status = new Status(client);
    }


}